### ISSUE TITLE
Loading a clip - crash

### ISSUE THREAD

**Issue by ObscenityIB** [andre-tm-hui/ReVox#3]
There don't seem to be any logs or settings for logging, but when an mp3 is loaded, the application crashes.

Opening the application again shows the waveform of the sound on the binding.

**Comment by andre-tm-hui** [comment]
Hi, this issue should be fixed in the next release - the problem stems from the code previously being unable to deal with mono (1-channel) audio clips. See e09abcb376c1d19c60213ae82cd4a9c4edfd5c1a. I will provide this release soon.

Regarding logs, I will add that to the list of things to add.
