### ISSUE TITLE
Playing a sound - no audio

### ISSUE THREAD

**Issue by ObscenityIB** [andre-tm-hui/ReVox#4]
Related to previous issue, after playing the sound, no matter which audio device is selected, nothing happens.

It could be playing, but there is no visual indicator of that, pressing the play icon has no effect.

**Comment by andre-tm-hui** [comment]
Does this occur only with the sound that you just imported? Or do other sounds still work?

**Comment by ObscenityIB** [comment]
It does occur with any sound I have, that said they are all mono, I will split them to stereo.

**Comment by andre-tm-hui** [comment]
I've added a new pre-release that fixes the file loading on my end. Please let me know if it works for you.

**Comment by andre-tm-hui** [comment]
Made a mistake in generating the setup file. Fixed now if you'd like to try it.
