### ISSUE TITLE
Not working Windows 7

### ISSUE THREAD

**Issue by Mistymimi** [andre-tm-hui/ReVox#8]
Getting the error
"The application was unable to start correctly (0xc0000005)" 

I used the ReVox_v0.2_setup.exe on my E drive and restarted my computer after encountering this issue. It persists. The drive was succesfully installed so it doesn't seem to be that. Upon looking back at the github repo, the requirement says that it is windows 10, hopefully other windows get support soon. Decided to still submit the issue so that others can see it if they are in the same boat and also could maybe hint at what is going wrong here when windows 7 is supported in the future.

**Comment by andre-tm-hui** [comment]
Thanks for downloading and bringing this up. 
As far as I know, the version of Qt used to build the app is incompatible with Windows 7, moreover the app needs to be built in Windows 7 in order to support it. 
I'm currently not planning to support Windows 7, unless there is a large demand for it.
